services:
  app:
    image: httpd:latest
    container_name: mirandas-apache
    volumes:
      - type: bind
        source: ./public-html/
        target: /usr/local/apache2/htdocs/
    ports:
      - '8080:80'
